In [1]:
import numpy as np
import tensorflow as tf

# Step 1: Create a small dataset using NumPy
np.random.seed(42)
input_data = np.random.randint(1, 100, size=(4, 5)).astype(np.float32)

print("Original Input:")
print(input_data)

# Step 2: Apply Batch Normalization
batch_norm = tf.keras.layers.BatchNormalization()
batch_output = batch_norm(input_data, training=True)

print("\nBatch Normalization Output:")
print(batch_output.numpy())

# Step 3: Apply Layer Normalization
layer_norm = tf.keras.layers.LayerNormalization()
layer_output = layer_norm(input_data)

print("\nLayer Normalization Output:")
print(layer_output.numpy())

# Step 4: Comparison
print("\nComparison:")
print("1. Batch Normalization normalizes data across the batch for each feature.")
print("2. Layer Normalization normalizes data across the features of each individual sample.")
print("3. Batch Normalization depends on the batch size, while Layer Normalization works independently of batch size.")

Original Input:
[[52. 93. 15. 72. 61.]
 [21. 83. 87. 75. 75.]
 [88. 24.  3. 22. 53.]
 [ 2. 88. 30. 38.  2.]]

Batch Normalization Output:
[[ 0.34510362  0.7516792  -0.5823407   0.9000547   0.48072648]
 [-0.6058486   0.3937366   1.6538475   1.033396    0.98866415]
 [ 1.4494354  -1.7181242  -0.9550387  -1.3223026   0.19047654]
 [-1.1886903   0.5727079  -0.11646813 -0.61114824 -1.6598673 ]]

Layer Normalization Output:
[[-0.25639224  1.3363471  -1.6937423   0.5205538   0.09323359]
 [-1.962309    0.61530066  0.78159785  0.28270578  0.28270578]
 [ 1.6851157  -0.4718324  -1.1795809  -0.539237    0.50553477]
 [-0.9509679   1.7751402  -0.06339788  0.19019353 -0.9509679 ]]

Comparison:
1. Batch Normalization normalizes data across the batch for each feature.
2. Layer Normalization normalizes data across the features of each individual sample.
3. Batch Normalization depends on the batch size, while Layer Normalization works independently of batch size.
